const router             = require('express').Router();
const { ethers }         = require('ethers');
const crypto             = require('crypto');
const VerificationRecord = require('../models/VerificationRecord');
const AntiqueItem        = require('../models/AntiqueItem');
const Certificate        = require('../models/Certificate');

// Load the ABI generated by Hardhat after compilation
const contractABI = require(
  '../artifacts/contracts/AntiqueVerification.sol/AntiqueVerification.json'
).abi;

// Connect to Sepolia via Alchemy
const provider = new ethers.JsonRpcProvider(process.env.ALCHEMY_SEPOLIA_URL);

// The signer is your deployer wallet — it pays the gas fee for each transaction
const signer   = new ethers.Wallet(process.env.DEPLOYER_PRIVATE_KEY, provider);

// Connect to your deployed contract using its address and ABI
const contract = new ethers.Contract(
  process.env.CONTRACT_ADDRESS,
  contractABI,
  signer
);

// POST /api/verifications — verifier submits a decision
router.post('/', async (req, res) => {
  try {
    const { itemId, verifiedBy, decision, notes, authenticityScore } = req.body;

    // ── STEP 1: Hash the full MongoDB verification data
    // This creates a fingerprint of the off-chain data
    const dataToHash = JSON.stringify({
      itemId,
      decision,
      notes,
      authenticityScore,
      timestamp: new Date().toISOString()
    });
    const metadataHash = crypto
      .createHash('sha256')
      .update(dataToHash)
      .digest('hex');

    // ── STEP 2: Call the smart contract on Sepolia
    // This is a real Ethereum transaction — costs a small amount of test ETH
    console.log('Sending transaction to Sepolia...');
    const tx = await contract.verifyItem(
      itemId,
      decision === 'approved',  // converts to boolean for Solidity
      metadataHash
    );

    // ── STEP 3: Wait for the transaction to be mined (~15 seconds)
    console.log('Waiting for transaction to be mined...');
    const receipt = await tx.wait();
    const txHash  = receipt.hash;
    console.log('Transaction mined! Hash:', txHash);

    // ── STEP 4: Save verification record to MongoDB
    const verification = await VerificationRecord.create({
      itemId,
      verifiedBy,
      decision,
      notes,
      authenticityScore,
      blockchainRef: txHash  // real Ethereum transaction hash
    });

    // ── STEP 5: Update the antique item status
    await AntiqueItem.findByIdAndUpdate(itemId, {
      status: decision === 'approved' ? 'verified' : 'rejected'
    });

    // ── STEP 6: Generate certificate if approved
    let certificate = null;
    if (decision === 'approved') {
      const item = await AntiqueItem.findById(itemId);
      const certNumber = 'CERT-' + new Date().getFullYear() + '-' +
                          String(Math.floor(Math.random() * 99999)).padStart(5, '0');
      certificate = await Certificate.create({
        itemId,
        verificationId: verification._id,
        certificateNumber: certNumber,
        blockHash: txHash,
        issuedTo: item.submittedBy
      });
    }

    // ── STEP 7: Return everything to the frontend
    res.status(201).json({
      verification,
      txHash,
      metadataHash,
      etherscanUrl: `https://sepolia.etherscan.io/tx/${txHash}`,
      certificate
    });

  } catch (err) {
    console.error('Verification error:', err);
    res.status(500).json({ error: err.message });
  }
});

// GET /api/verifications/chain/:itemId — read record directly from blockchain
router.get('/chain/:itemId', async (req, res) => {
  try {
    const record = await contract.getRecord(req.params.itemId);
    res.json({
      itemId:       record.itemId,
      verifier:     record.verifier,
      isAuthentic:  record.isAuthentic,
      metadataHash: record.metadataHash,
      timestamp:    new Date(Number(record.timestamp) * 1000).toISOString()
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/verifications/:itemId — get verification from MongoDB
router.get('/:itemId', async (req, res) => {
  try {
    const verification = await VerificationRecord
      .findOne({ itemId: req.params.itemId })
      .populate('verifiedBy', 'name email');
    if (!verification) return res.status(404).json({ error: 'No verification found' });
    res.json(verification);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;