const { ethers } = require('ethers');
const crypto = require('crypto');

// Load the ABI generated by Hardhat after compilation
const contractABI = require(
  '../artifacts/contracts/AntiqueVerification.sol/AntiqueVerification.json'
).abi;

// Connect to Sepolia via Alchemy
const provider = new ethers.JsonRpcProvider(process.env.ALCHEMY_SEPOLIA_URL);

// The signer is your deployer wallet — it pays the gas fee for each transaction
const signer = new ethers.Wallet(process.env.DEPLOYER_PRIVATE_KEY, provider);

// Connect to your deployed contract using its address and ABI
const contract = new ethers.Contract(
  process.env.CONTRACT_ADDRESS,
  contractABI,
  signer
);

/**
 * Generate SHA-256 hash from antique data
 * @param {Object} data - The verification data to hash
 * @returns {string} - The SHA-256 hex hash
 */
function generateMetadataHash(data) {
  const dataToHash = JSON.stringify(data);
  return crypto
    .createHash('sha256')
    .update(dataToHash)
    .digest('hex');
}

/**
 * Submit verification to blockchain
 * @param {string} itemId - MongoDB item ID
 * @param {boolean} isAuthentic - Authentication decision
 * @param {string} metadataHash - SHA-256 hash of verification data
 * @returns {Promise<Object>} - Transaction receipt and hash
 */
async function submitVerificationToBlockchain(itemId, isAuthentic, metadataHash) {
  try {
    console.log('Sending transaction to Sepolia...');
    const tx = await contract.verifyItem(
      itemId,
      isAuthentic,
      metadataHash
    );

    console.log('Waiting for transaction to be mined...');
    const receipt = await tx.wait();
    const txHash = receipt.hash;
    console.log('Transaction mined! Hash:', txHash);

    return {
      txHash,
      receipt,
      success: true
    };
  } catch (error) {
    console.error('Blockchain submission error:', error);
    throw new Error(`Failed to submit verification: ${error.message}`);
  }
}

/**
 * Retrieve verification record directly from blockchain
 * @param {string} itemId - MongoDB item ID
 * @returns {Promise<Object>} - Verification record from chain
 */
async function getVerificationFromChain(itemId) {
  try {
    const record = await contract.getRecord(itemId);
    return {
      itemId: record.itemId,
      verifier: record.verifier,
      isAuthentic: record.isAuthentic,
      metadataHash: record.metadataHash,
      timestamp: new Date(Number(record.timestamp) * 1000).toISOString(),
      blockHash: record.blockHash,
      exists: record.exists
    };
  } catch (error) {
    console.error('Error retrieving from chain:', error);
    throw new Error(`Failed to retrieve verification: ${error.message}`);
  }
}

/**
 * Check if an item has been verified on-chain
 * @param {string} itemId - MongoDB item ID
 * @returns {Promise<boolean>} - True if verified
 */
async function isItemVerifiedOnChain(itemId) {
  try {
    return await contract.isVerified(itemId);
  } catch (error) {
    console.error('Error checking verification status:', error);
    throw new Error(`Failed to check verification: ${error.message}`);
  }
}

/**
 * Generate Etherscan URL for a transaction
 * @param {string} txHash - Transaction hash
 * @returns {string} - Etherscan URL
 */
function getEtherscanUrl(txHash) {
  return `https://sepolia.etherscan.io/tx/${txHash}`;
}

module.exports = {
  generateMetadataHash,
  submitVerificationToBlockchain,
  getVerificationFromChain,
  isItemVerifiedOnChain,
  getEtherscanUrl,
  contract,
  provider
};
